### ISSUE TITLE
Firebase SPM?

### ISSUE THREAD

**Issue by yyokii** [yyokii/SubscMemo#4]
```
packages:
  CombineFirebase:
    url: "https://github.com/rever-ai/CombineFirebase"
    version: 0.3.0  
  Firebase:
    url: "https://github.com/firebase/firebase-ios-sdk.git"
    version: 8.3.0

~

    dependencies:
      - package: CombineFirebase
        product: CombineFirebase/Firestore
        product: CombineFirebase/Auth
      - package: Firebase
        product: Firebase/Auth
        product: Firebase/Analytics
        product: Firebase/Firestore
        product: FirebaseFirestoreSwift-Beta
      - package: Tagged

```

```
Dependencies could not be resolved because root depends on 'CombineFirebase' 0.3.0.
'CombineFirebase' cannot be used because 'CombineFirebase' depends on 'firebase-ios-sdk' 7.3.1..<8.0.0 and root depends on 'firebase-ios-sdk' 8.3.0.
```

if we use Firebase with SPM, we need to make CombineFirebase our own
